#!/bin/bash -e
mkdir /mnt/rpi/ || true
mount 2013-09-25-wheezy-raspbian.img -o loop,offset=$((122880*512)),rw /mnt/rpi/
mount 2013-09-25-wheezy-raspbian.img -o loop,offset=$((8192*512)),rw /mnt/rpi/boot/
function doit () {
	mount --bind /$1 $1/
}
cd /mnt/rpi/
cp -vi /usr/bin/qemu-static-arm-binfmt usr/bin/
/etc/init.d/qemu-binfmt start
for x in dev proc sys dev/pts
	do doit $x
done
